server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003.com  #eureka服务器的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己，他本来就是服务器，不用注册自己
    fetch-registry: false #如果未false，则表示自己是注册中心
    service-url:  #监控页面，打开源码，发现defaultZone默认是http://localhost:8761/eureka/  但是我们要自己定义
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
